#!/bin/bash
# Apply tagging standard to all modules
# Generated by Claude Code - 2026-02-27

set -e

cd /home/ubuntu/git/azure-infra

# Define tag values per module
declare -A ENV_TAGS=(
  [logging]="shared"
  [main]="shared"
  [dev]="development"
  [prod]="production"
  [identity]="shared"
  [firewall]="shared"
  [dashboard]="shared"
)

declare -A DATA_CLASS=(
  [logging]="confidential"
  [main]="internal"
  [dev]="internal"
  [prod]="phi"
  [identity]="confidential"
  [firewall]="internal"
  [dashboard]="internal"
)

declare -A COMPLIANCE=(
  [logging]="hipaa-soc2-hitrust"
  [main]="soc2-hitrust"
  [dev]="soc2-hitrust"
  [prod]="hipaa-soc2-hitrust"
  [identity]="hipaa-soc2-hitrust"
  [firewall]="soc2-hitrust"
  [dashboard]="soc2-hitrust"
)

# Function to add locals block to main.tf
add_locals() {
  local module=$1
  local env=${ENV_TAGS[$module]}
  local data_class=${DATA_CLASS[$module]}
  local compliance=${COMPLIANCE[$module]}

  cat > "${module}/tags_local.tf" << EOF
# Required tags per /git/infrastructure-docs/compliance/tagging-standard.md
locals {
  required_tags = {
    environment          = "${env}"
    owner                = "it-security"
    managed-by           = "terraform"
    data-classification  = "${data_class}"
    cost-center          = "it"
    compliance-scope     = "${compliance}"
  }
}
EOF

  echo "✓ Created tags_local.tf in $module"
}

# Create locals blocks for all modules
for module in logging main dev prod identity firewall dashboard; do
  if [ -d "$module" ]; then
    add_locals "$module"
  fi
done

echo ""
echo "✓ Locals blocks created in all 7 modules"
echo ""
echo "Next steps:"
echo "1. Manually add 'tags = local.required_tags' to resources"
echo "2. Or use merge(local.required_tags, {}) for resource-specific tags"
echo "3. Exclude azurerm_firewall and azurerm_network_security_* resources"
echo "4. Run 'terraform plan' in each module to verify zero destroys"
